//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorPayment
    {
        public long ContractorPaymentId { get; set; }
        public long ContractorId { get; set; }
        public long JobId { get; set; }
        public double Amount { get; set; }
        public System.DateTime PaymentDate { get; set; }
    }
}
