//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public long ExpenseId { get; set; }
        public Nullable<long> VehicleId { get; set; }
        public string ExpenseTitle { get; set; }
        public string ExpenseType { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
