//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public long JobId { get; set; }
        public string JobTitle { get; set; }
        public long TobType { get; set; }
        public long Contractor { get; set; }
        public double Amount { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Contractor Contractor1 { get; set; }
    }
}
