//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long PaymentId { get; set; }
        public long VehicleId { get; set; }
        public long SaleId { get; set; }
        public string Installment { get; set; }
        public double Amount { get; set; }
        public System.DateTime DatePayed { get; set; }
    
        public virtual SaleVehicle SaleVehicle { get; set; }
    }
}
