//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleSeller
    {
        public long VehicleSellerId { get; set; }
        public string SellerName { get; set; }
        public string SellerContactNumber { get; set; }
        public string SellerType { get; set; }
        public string SellerAddress { get; set; }
        public string VehicleNumber { get; set; }
    }
}
